version: "3.8"
services:
  app:
    build: .
    ports:
      - 8000:8000
    volumes:
      - .:/app
    environment:
      - DATABASE_URL=postgresql://postgres:localhost@db:5432/codeshare
    depends_on:
      - db
  db:
    image: postgres:13-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=codeshare

volumes:
  postgres_data:
