
name: dependencies check

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 2
      matrix:
        python-versions: ["3.9", "3.10"]
        poetry-version: ["1.1.12"]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-versions }}
        uses: actions/setup-python@v3
        with: 
          python-version: ${{ matrix.python-versions }}
      - uses: Gr1N/setup-poetry@v7
        with:
          poetry-version: ${{ matrix.poetry-version }}
      - run: poetry install 